const styles = {
  BoxContainer: {
    backgroundColor: "background.default",
    borderRadius: "13px",
    boxShadow: theme => `0px 6px 40px ${theme.palette.primary.box_show_blog}`,
    overflow: "hidden",
    height: "100%",
    display: "flex",
    flexDirection: "column",
    justifyContent: "space-between", 
  },
  Image: {
    borderRadius: "5px",
    width: "100%",
    height: { xs: "150px", sm: "200px" },
    objectFit: "cover",
  },
  Content: {
    padding: { xs: "1em", sm: "1em" },
    position: "relative",
    flexGrow: 1, 
    display: "flex",
    flexDirection: "column",
    justifyContent: "flex-start",
    textAlign: "left",
    width: "100%",
    height: "100%",
  },
  Category: {
    position: "absolute",
    top: { xs: "-5%", sm: "-3%" },
    backgroundColor: "background.default",
    padding: "5px 15px",
    borderRadius: "5px",
    transform: "translateY(-50%)",
    boxShadow: theme => `0 0 14px ${theme.palette.primary.box_shadow_blog_2}`,
  },
  Title: {
    fontWeight: 700,
    letterSpacing: "0.5px",
    fontSize: {
      xs: "0.5rem",
      sm: "1.1rem",
    },
    width: "100%",
    textAlign: "left",
    minHeight: {
      xs: "1em",
      sm: "2.2em",
    },
    display: "flex",
    alignItems: "center",
  },
  TimeText: {
    fontSize: "0.875rem",
    color: "text.secondary",
    textAlign: "left",
    width: "100%",
  },
  Button: {
    backgroundColor: "#213689",
    color: "#ffffff",
    padding: "10px",
    justifyContent: "center",
    marginTop: "auto",
    borderRadius: "5px",
    fontSize: { xs: "12px", sm: "14px" },
    fontWeight: 500,
    svg: {
      color: "background.default",
      fontSize: { xs: "14px", sm: "17px" },
      marginLeft: "5px",
      marginBottom: "-1px",
    },
    transition: "0.3s ease",
    "&:hover": {
      backgroundColor: "primary.main",
      color: "background.default",
    },
    alignSelf: "flex-start",
  },
};

export default styles;
